QAWebsite/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace QAWebsite.Models
{
    public class Question
    {
        public Question()
        {
            Answers = new List<Answer>();
            QuestionComments = new List<QuestionComment>();
            Date = System.DateTime.Now;
            QuestionTags = new HashSet<QuestionTag>();
        }
        public int Id { get; set; }
        [Required]
        [MinLength(3),MaxLength(128)]
        public string Title { get; set; }
        [Required]
        [MinLength(3), MaxLength(512)]
        public string Content { get; set; }
        public DateTime Date { get; set; }
        public int QuestionVote { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<QuestionTag> QuestionTags { get; set; }
    }
}

QAWebsite/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using QAWebsite.Models;

namespace QAWebsite.Controllers
{
    public class AnswersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Question).Include(a => a.User);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // GET: Answers/Create
        [Authorize]
        public ActionResult Create()
        {
            //Question question = db.Questions.Find(QuestionId);
            //if (question == null)
            //{
            //    return HttpNotFound();
            //}
            //ViewBag.QuestionTitle = question.Title;
            //ViewBag.UserId = User.Identity.GetUserId();
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int QuestionId, string Content)
        {
            Question question = db.Questions.Find(QuestionId);
            if (question == null)
            {
                return HttpNotFound();
            }
            Answer answer = new Answer();
            answer.Content = Content;
            answer.QuestionId = QuestionId;
            answer.UserId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.QuestionTitle = question.Title;
            ViewBag.UserId = User.Identity.GetUserId();

            //ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Title", answer.QuestionId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Title", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,QuestionId,UserId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Title", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QAWebsite/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using QAWebsite.Models;

namespace QAWebsite.Controllers
{
    
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Questions
        public ActionResult Index(int? page,bool? sortByNumber)
        {
            ViewBag.sortByNumber = sortByNumber;
            // List of question
            var questions = db.Questions.Include(q => q.User);

            // Which number it is.
            int pageNumber = page ?? 1;

            // Each page show 10 questions 
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);

            if (sortByNumber == true)
            {
                // Order by Number Of Answers.
                ViewBag.Sorted = "Sorted By Number Of Answers.";
                questions = questions.OrderByDescending(q => q.Answers.Count);
            }
            else
            {
                // Order by date.
                ViewBag.Sorted = "Sorted By Date";
                questions = questions.OrderByDescending(q => q.Date);
            }
            

            // Use ToPagedList.
            IPagedList<Question> pagedList = questions.ToPagedList(pageNumber, pageSize);

            return View(pagedList);
        }
        public ActionResult QuestionsInATag(int? page, bool? sortByNumber, int tagId)
        {
            ViewBag.sortByNumber = sortByNumber;
            ViewBag.tagId = tagId;
            ViewBag.tagName = db.Tags.Find(tagId).Name;
            // List of question
            var questions = db.Questions.Include(q => q.User);
            questions = questions.Where(q => q.QuestionTags.Any(qt => qt.TagId == tagId));

            // Which number it is.
            int pageNumber = page ?? 1;

            // Each page show 10 questions 
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);

            if (sortByNumber == true)
            {
                // Order by Number Of Answers.
                ViewBag.Sorted = "Sorted By Number Of Answers.";
                questions = questions.OrderByDescending(q => q.Answers.Count);
            }
            else
            {
                // Order by date.
                ViewBag.Sorted = "Sorted By Date";
                questions = questions.OrderBy(q => q.Date);
            }

            // Use ToPagedList.
            IPagedList<Question> pagedList = questions.ToPagedList(pageNumber, pageSize);

            return View(pagedList);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.AcceptedAnswer = question.Answers.Any(a => a.Accepted == true);
            return View(question);
        }
        #region
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Details(int id, string answer_Content)
        //{
        //    Question question = db.Questions.Find(id);
        //    if (question == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        Answer answer = new Answer();
        //        answer.QuestionId = id;
        //        answer.Content = answer_Content;
        //        answer.UserId = User.Identity.GetUserId();
        //        db.Answers.Add(answer);
        //        db.SaveChanges();
        //        return RedirectToAction("Details",new { id });
        //    }

        //    return View(question);
        //}
        #endregion
        [Authorize]
        public ActionResult AddComment()
        {
            return View();
        }

        // POST: QuestionComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(int QuestionId, string Comment)
        {
            QuestionComment questionComment = new QuestionComment();
            questionComment.QuestionId = QuestionId;
            questionComment.Comment = Comment;
            questionComment.UserId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.QuestionComments.Add(questionComment);
                db.SaveChanges();
                return RedirectToAction("Details",new { id = QuestionId });
            }
            return View(questionComment);
        }
        [Authorize]
        public ActionResult AnswerQuestion(int? QuestionId)
        {
            if (QuestionId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(QuestionId);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionTitle = question.Title;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnswerQuestion(int QuestionId, string Content)
        {
            Question question = db.Questions.Find(QuestionId);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionTitle = question.Title;

            Answer answer = new Answer();
            answer.QuestionId = QuestionId;
            answer.Content = Content;
            answer.UserId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = QuestionId });
            }
            return View(answer);
        }
        [Authorize]
        public ActionResult AddAnswerComment()
        {
            return View();
        }

        // POST: QuestionComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnswerComment(int QuestionId,int AnswerId, string Comment)
        {
            AnswerComment answerComment = new AnswerComment();
            answerComment.AnswerId = AnswerId;
            answerComment.Comment = Comment;
            answerComment.UserId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.AnswerComments.Add(answerComment);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = QuestionId });
            }
            return View(answerComment);
        }
        [Authorize]
        public ActionResult VoteUp(int id)
        {
            var question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.GetUserId() != question.UserId)
            {
                question.QuestionVote++;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id });
        }
        [Authorize]
        public ActionResult VoteDown(int id)
        {
            var question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.GetUserId() != question.UserId)
            {
                question.QuestionVote--;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id });
        }
        [Authorize]
        public ActionResult AnswerVoteUp(int id,int answerId)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            Answer answer = db.Answers.Find(answerId);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.GetUserId() != answer.UserId)
            {
                answer.AnswerVote++;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id });
        }
        [Authorize]
        public ActionResult AnswerVoteDown(int id,int answerId)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            Answer answer = db.Answers.Find(answerId);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.GetUserId() != answer.UserId)
            {
                answer.AnswerVote--;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id });
        }
        [Authorize]
        public ActionResult MarkAnswer(int id, int answerId)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            Answer answer = db.Answers.Find(answerId);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.GetUserId() == question.UserId)
            {

QAWebsite/Views/Questions/AddAnswerComment.cshtml
@model QAWebsite.Models.AnswerComment
@{
    ViewBag.Title = "AddAnswerComment";
}

<h2>Add Answer Comment</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QAWebsite/Views/Questions/AddComment.cshtml
@model QAWebsite.Models.QuestionComment
@{
    ViewBag.Title = "AddComment";
}

<h2>Add a Comment</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QAWebsite/Views/Questions/AnswerQuestion.cshtml
@model QAWebsite.Models.Answer
@{
    ViewBag.Title = "AnswerQuestion";
}

<h2>Answer Question</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Answer Question</h4>
        <hr />
                <div class="form-group">
            @Html.Label("QuestionTitle", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @ViewBag.QuestionTitle
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.QuestionId, "QuestionId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("QuestionId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.QuestionId, "", new { @class = "text-danger" })
                </div>
            </div>*@


        @*<div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>*@



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QAWebsite/Views/Questions/Create.cshtml
@model QAWebsite.Models.Question

@{
    ViewBag.Title = "Create";
}

<h2>Ask Question</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" }, style = "height:150px;width:300px" })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
            @Html.Label("Tags", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TagId", (MultiSelectList)ViewBag.TagId, htmlAttributes: new { @class = "form-control", multiple = "multiple", size = 8 })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QAWebsite/Views/Questions/Delete.cshtml
@model QAWebsite.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QAWebsite/Views/Questions/Details.cshtml
@model QAWebsite.Models.Question

@{
    ViewBag.Title = "Details";
}

<p>
    @Html.ActionLink("Ask Question", "Create")
</p>
<p>
    @Html.ActionLink("Back To Index", "Index")
</p>
<div style="background-color: aliceblue">
    <h1>@Model.Title</h1>

    <div style="text-align:end">
        Asked at @Model.Date
    </div>
    <hr />
    <div style="display:flex;flex-wrap:wrap">
        <div style="width:5%;text-align:center">
            <div>
                @Html.ActionLink("▲", "VoteUp", new { id = Model.Id })

            </div>
            <div>@Model.QuestionVote</div>
            <div>@Html.ActionLink("▼", "VoteDown", new { id = Model.Id })</div>
        </div>
        <div style="width:95%">
            <div>
                @Model.Content
            </div>
            <div style="text-align:end">
                @Model.User.Email  REP:<span style="color:red">@Model.User.CalculateVotes()</span>
            </div>
            <div style="text-align:end">
                @foreach (var tag in Model.QuestionTags)
                {
                    <span style="background-color:aquamarine">@Html.ActionLink(tag.Tag.Name, "QuestionsInATag", new { tagId = tag.TagId })</span>

                }
            </div>
            <hr />
            <div style="background-color:cornsilk">
                @if (Model.QuestionComments.Count > 0)
                {
                    <div>
                        @foreach (var (qc, index) in Model.QuestionComments.Select((value, i) => (value, i)))

                        {
                            <div style="width:90%;padding-left:20px;">
                                @(index+1).
                                @qc.Comment
                                <br />
                                <div style="text-align:end">
                                    @*@qc.User.UserName*@ at @qc.Date
                                </div>
                            </div>
                            <hr style="width:90%;padding-left:20px;" />
                        }
                    </div>
                }
                <div style="width:90%;padding-left:20px;">
                    @Html.ActionLink("add a comment", "AddComment", new { QuestionId = Model.Id })
                </div>
                <hr style="margin-top:0px" />
            </div>

        </div>
    </div>
</div>


<h4 style="color: Blue;">@Model.Answers.Count() Answers</h4>
<hr />
@foreach (var item in Model.Answers.OrderByDescending(a => a.AnswerDate).OrderByDescending(a => a.Accepted))
{
    <div style="display:flex;flex-wrap:wrap">
        <div style="width:5%;text-align:center">
            <div>@Html.ActionLink("▲", "AnswerVoteUp", new { id = Model.Id, answerId = item.Id })</div>
            <div>@item.AnswerVote</div>
            <div>@Html.ActionLink("▼", "AnswerVoteDown", new { id = Model.Id, answerId = item.Id })</div>
            @if (item.Accepted == true)
            {
                <div style="color:red">★★★</div>
            }
            else
            {
                if (@ViewBag.AcceptedAnswer == false & User.Identity.Name == Model.User.UserName)
                {
                    <div>@Html.ActionLink("Mark", "MarkAnswer", new { id = Model.Id, answerId = item.Id })</div>
                }
            }
        </div>
        <div style="width: 95%;background-color: azure">
            <div>
                @item.Content
            </div>
            <div style="text-align:end">
                @item.User.Email REP:<span style="color:red">@item.User.CalculateVotes()</span>
            </div>
            <div style="text-align:end">
                @item.AnswerDate
            </div>
            <hr />
            <div style="background-color:cornsilk">
                @if (item.AnswerComments.Count > 0)
                {
                    <div>
                        @foreach (var (ac, index) in item.AnswerComments.Select((value, i) => (value, i)))
                        {
                            <div style="width:90%;padding-left:20px;">
                                @(index+1).
                                @ac.Comment
                                <br />
                                <div style="text-align:end">
                                    @ac.User.Email at @ac.Date
                                </div>
                            </div>
                            <hr style="width:90%;padding-left:20px;" />
                        }
                    </div>
                }
                <div style="width:90%;padding-left:20px;">
                    @Html.ActionLink("add a comment", "AddAnswerComment", new { QuestionId = Model.Id, AnswerId = item.Id })
                </div>
            </div>


        </div>
    </div>
    <hr />
}


<button>
    @Html.ActionLink("Post Answer", "AnswerQuestion", new { QuestionId = Model.Id })
</button>
@*<button>
    @Html.ActionLink("Post Answer", "Create","Answers", new { QuestionId = Model.Id },null)
</button>*@

<hr />

<div>
    @Html.ActionLink("Back To Index", "Index")
</div>

QAWebsite/Views/Questions/Edit.cshtml
@model QAWebsite.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}